### ISSUE TITLE
Some ideas for hero image

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/cloud-init.org#29]
Could we potentially use one of the following, @pmahnke 

- hero in http://www.ubuntu.com/cloud/public-cloud

- image in Bootstack row http://www.ubuntu.com/cloud/openstack (maybe without the CoF if necessary?)

- hero in http://www.ubuntu.com/cloud/storage

**Comment by barrymcgee** [comment]
@yaili Is this issue now obsolete?

**Comment by yaili** [comment]
Yes
