### ISSUE TITLE
Update favicon

### ISSUE THREAD

**Issue by anthonydillon** [ubuntudesign/cloud-init.org#37]
![favicon](https://cloud.githubusercontent.com/assets/1413534/12789654/980920e6-ca96-11e5-8cfd-8eaa11ae4e22.png)

Added some whiteness.

**Comment by barrymcgee** [comment]
@yaili Is this request still valid? You can see demo site here: http://barrymcgee.github.io/cloud-init/

If so - I'll need someone to manipulate and provide the favicon file as that's beyond my designer chops..

**Comment by yaili** [comment]
It was @anthonydillon's request. Can you use the file he attached?

**Comment by barrymcgee** [comment]
@yaili @anthonydillon Sorry - misread that.. sorted now!

**Comment by anthonydillon** [comment]
LGTM :+1:
